<!DOCTYPE html>
<head>
    <title>Shopping List</title>
</head>
<body>
    <pre>
        <?php echo json_encode($shopping_list) ?>
    </pre>

    <div id="page">
        <div id="header">
            <h1>Shopping List</h1>
        </div>
        <div id="main">
            <!-- part 1: the errors -->
            <?php if (count($errors) > 0) : ?>
                <h2>Errors</h2>
                <ul>
                    <?php foreach ($errors as $error) : ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <!-- part 2: the Shopping List -->
            <h2>Items to buy</h2>
            <?php if (count($shopping_list) == 0) : ?>
                <p>There are no items in your shopping list.</p>
            <?php else: ?>
                <table>
                    <?php foreach ($shopping_list as $id => $item) : ?>
                        <tr>
                            <td><?php echo ($id + 1) . "."; ?> </td> 
                            <td> <?= $item; ?></td> 
                            <td>
                                <!-- part 2a: the delete button form -->
                                <form action="." method="post" >
                                    <input type="hidden" name="itemid" value="<?= $id; ?>"/>
                                    <input type="submit" name="btnDelete" value="Delete"/>
									<input type="hidden" name="action" value="delete_item" />
                                </form>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <?php endif; ?>
            <br />

            <!-- part 3: the add form -->
            <h2>Add Item</h2>
            <form action="." method="post" >
				<input type="hidden" name="action" value="add_item" />
                <label>Item:</label>
                <input type="text" name="newitem" id="newitem"/> 
                <label>&nbsp;</label>
                <input type="submit" name="btnAdd" value="Add Item"/><br />
            </form>
            <br />
        </div><!-- end main -->
    </div><!-- end page -->
</body>
</html>